name: CI
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install -g yarn
          yarn install
          npm run docs:build
          npm run docs:deploy

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4.3.3
      #   with:
      #     branch: gh-pages
      #     folder: docs
